###############################################################################
# CDRGoat AI – Scenario 1: Prompt Injection → SQL Injection → SSH Exfiltration
#
# Infrastructure: VPC + EC2 (t3.large) + local MySQL
# The EC2 runs a Flask chat portal backed by Claude Code (/loop) as the AI
# agent. The agent queries MySQL for appointment data. Through prompt
# injection the attacker tricks the agent into running LOAD_FILE() via SQL,
# exfiltrating the host SSH private key, and gaining shell access.
###############################################################################

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = ">= 4.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

# ---------------------------------------------------------------------------
# Variables
# ---------------------------------------------------------------------------

variable "aws_region" {
  description = "AWS region to deploy into"
  type        = string
  default     = "us-east-1"
}

variable "attack_whitelist" {
  description = "List of CIDRs allowed to reach the EC2 instance (HTTP + SSH)"
  type        = list(string)
}

variable "bedrock_model_id" {
  description = "Bedrock model ID for Claude"
  type        = string
  default     = "us.anthropic.claude-haiku-4-5-20251001-v1:0"
}


# ---------------------------------------------------------------------------
# Data sources
# ---------------------------------------------------------------------------

data "aws_ami" "ubuntu" {
  most_recent = true
  owners      = ["099720109477"] # Canonical

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

data "aws_availability_zones" "available" {
  state = "available"
}

# ---------------------------------------------------------------------------
# Networking
# ---------------------------------------------------------------------------

resource "aws_vpc" "main" {
  cidr_block           = "10.30.0.0/16"
  enable_dns_support   = true
  enable_dns_hostnames = true

  tags = { Name = "cdrgoat-ai-1-vpc" }
}

resource "aws_subnet" "public" {
  vpc_id                  = aws_vpc.main.id
  cidr_block              = "10.30.0.0/24"
  availability_zone       = data.aws_availability_zones.available.names[0]
  map_public_ip_on_launch = true

  tags = { Name = "cdrgoat-ai-1-public" }
}

resource "aws_internet_gateway" "igw" {
  vpc_id = aws_vpc.main.id
  tags   = { Name = "cdrgoat-ai-1-igw" }
}

resource "aws_route_table" "public" {
  vpc_id = aws_vpc.main.id

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.igw.id
  }

  tags = { Name = "cdrgoat-ai-1-rt" }
}

resource "aws_route_table_association" "public" {
  subnet_id      = aws_subnet.public.id
  route_table_id = aws_route_table.public.id
}

# ---------------------------------------------------------------------------
# Security group
# ---------------------------------------------------------------------------

resource "aws_security_group" "ec2" {
  name                   = "cdrgoat-ai-1-ec2"
  description            = "Allow HTTP + SSH from attacker"
  vpc_id                 = aws_vpc.main.id
  revoke_rules_on_delete = true

  ingress {
    description = "HTTP"
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = var.attack_whitelist
  }

  ingress {
    description = "SSH"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = var.attack_whitelist
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = { Name = "cdrgoat-ai-1-sg" }
}

# ---------------------------------------------------------------------------
# SSH key pair (generated by Terraform, private key lives on the EC2)
# ---------------------------------------------------------------------------

resource "tls_private_key" "ssh" {
  algorithm = "ED25519"
}

resource "aws_key_pair" "deployer" {
  key_name   = "cdrgoat-ai-1-key"
  public_key = tls_private_key.ssh.public_key_openssh
}

# ---------------------------------------------------------------------------
# Random password for MySQL
# ---------------------------------------------------------------------------

resource "random_password" "db" {
  length  = 20
  special = false
}

# ---------------------------------------------------------------------------
# IAM role for EC2 – Bedrock access for Claude Code
# ---------------------------------------------------------------------------

resource "aws_iam_role" "clinic" {
  name = "cdrgoat-ai-1-clinic"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action    = "sts:AssumeRole"
      Effect    = "Allow"
      Principal = { Service = "ec2.amazonaws.com" }
    }]
  })
}

resource "aws_iam_role_policy" "bedrock" {
  name = "bedrock-invoke"
  role = aws_iam_role.clinic.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = [
        "bedrock:InvokeModel",
        "bedrock:InvokeModelWithResponseStream"
      ]
      Resource = "*"
    }]
  })
}

resource "aws_iam_role_policy_attachment" "ssm" {
  role       = aws_iam_role.clinic.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}

resource "aws_iam_instance_profile" "clinic" {
  name = "cdrgoat-ai-1-clinic"
  role = aws_iam_role.clinic.name
}

# ---------------------------------------------------------------------------
# EC2 instance
# ---------------------------------------------------------------------------

locals {
  db_user = "clinicapp"
  db_pass = random_password.db.result
  db_name = "clinic_db"

  user_data = <<-EOT
#!/bin/bash
set -euxo pipefail
export DEBIAN_FRONTEND=noninteractive

# ── Wait for unattended-upgrades / dpkg lock ─────────────────────────────
systemctl stop unattended-upgrades 2>/dev/null || true
systemctl disable unattended-upgrades 2>/dev/null || true
while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 || fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do
  echo "Waiting for dpkg lock..."
  sleep 3
done
sleep 5

# ── System packages ──────────────────────────────────────────────────────
apt-get update -y
apt-get install -y python3-pip python3-venv mysql-server jq curl unzip openssh-server net-tools
pip3 install flask boto3

# ── MySQL setup ──────────────────────────────────────────────────────────
# Enable LOAD_FILE: set secure_file_priv to empty
cat >/etc/mysql/mysql.conf.d/loadfile.cnf <<'CNF'
[mysqld]
secure_file_priv = ""
local_infile     = 1
CNF

# Disable AppArmor for mysqld so LOAD_FILE can read outside /var/lib/mysql
ln -sf /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld 2>/dev/null || true

systemctl restart mysql
systemctl enable mysql

mysql -u root <<'SQL'
CREATE DATABASE IF NOT EXISTS ${local.db_name};
CREATE USER IF NOT EXISTS '${local.db_user}'@'localhost' IDENTIFIED BY '${local.db_pass}';
GRANT ALL PRIVILEGES ON ${local.db_name}.* TO '${local.db_user}'@'localhost';
GRANT FILE ON *.* TO '${local.db_user}'@'localhost';
FLUSH PRIVILEGES;

USE ${local.db_name};

CREATE TABLE IF NOT EXISTS specialists (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  name        VARCHAR(100) NOT NULL,
  specialty   VARCHAR(100) NOT NULL,
  room        VARCHAR(20)  NOT NULL,
  available   BOOLEAN DEFAULT TRUE,
  next_slot   DATETIME
);

CREATE TABLE IF NOT EXISTS appointments (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  patient_name  VARCHAR(100) NOT NULL,
  specialist_id INT NOT NULL,
  appointment   DATETIME NOT NULL,
  notes         TEXT,
  FOREIGN KEY (specialist_id) REFERENCES specialists(id)
);

INSERT INTO specialists (name, specialty, room, available, next_slot) VALUES
  ('Dr. Emily Carter',   'General Practitioner', 'A-101', TRUE,  '2026-05-15 09:00:00'),
  ('Dr. James Nguyen',   'Cardiology',           'B-205', TRUE,  '2026-05-15 10:30:00'),
  ('Dr. Sofia Ramirez',  'Dermatology',           'C-110', TRUE,  '2026-05-15 11:00:00'),
  ('Dr. Michael Chen',   'Orthopedics',           'D-302', FALSE, '2026-05-16 14:00:00'),
  ('Dr. Aisha Patel',    'Pediatrics',            'A-204', TRUE,  '2026-05-15 13:00:00');
SQL

# ── SSH key (the exfiltration target) ────────────────────────────────────
mkdir -p /home/ubuntu/.ssh
cp ${tls_private_key.ssh.private_key_openssh != "" ? "/dev/stdin" : "/dev/null"} /tmp/_placeholder || true

cat >/home/ubuntu/.ssh/id_ed25519 <<'SSHKEY'
${tls_private_key.ssh.private_key_openssh}
SSHKEY
chmod 600 /home/ubuntu/.ssh/id_ed25519
chown ubuntu:ubuntu /home/ubuntu/.ssh/id_ed25519

cat >>/home/ubuntu/.ssh/authorized_keys <<'AUTHKEY'
${tls_private_key.ssh.public_key_openssh}
AUTHKEY
chmod 600 /home/ubuntu/.ssh/authorized_keys
chown -R ubuntu:ubuntu /home/ubuntu/.ssh

# Make the key and directories traversable by MySQL for LOAD_FILE
chmod o+x /home/ubuntu /home/ubuntu/.ssh
chmod 644 /home/ubuntu/.ssh/id_ed25519

# ── Flask chat application ───────────────────────────────────────────────
mkdir -p /opt/clinic-chat/templates /opt/clinic-chat/messages

cat >/opt/clinic-chat/app.py <<'PY'
import os, json, time, glob, uuid
from flask import Flask, request, jsonify, render_template

app = Flask(__name__)
MSG_DIR   = "/opt/clinic-chat/messages"
os.makedirs(MSG_DIR, exist_ok=True)

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/chat", methods=["POST"])
def chat():
    data = request.get_json(force=True)
    user_msg = data.get("message", "").strip()
    if not user_msg:
        return jsonify({"error": "empty message"}), 400

    msg_id = str(uuid.uuid4())
    payload = {"id": msg_id, "role": "user", "content": user_msg, "ts": time.time()}
    with open(os.path.join(MSG_DIR, f"{msg_id}.json"), "w") as f:
        json.dump(payload, f)

    for _ in range(120):
        resp_path = os.path.join(MSG_DIR, f"{msg_id}_response.json")
        if os.path.exists(resp_path):
            with open(resp_path) as f:
                resp = json.load(f)
            os.remove(os.path.join(MSG_DIR, f"{msg_id}.json"))
            os.remove(resp_path)
            return jsonify({"response": resp["content"]})
        time.sleep(0.5)

    return jsonify({"error": "agent timeout"}), 504

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=80)
PY

cat >/opt/clinic-chat/templates/index.html <<'HTML'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>HealthFirst Medical Clinic</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Segoe UI', system-ui, sans-serif; background: #f0f4f8; height: 100vh; display: flex; flex-direction: column; }
  .header { background: linear-gradient(135deg, #1a73a7, #2596be); color: white; padding: 20px 30px; }
  .header h1 { font-size: 1.5rem; }
  .header p { font-size: 0.85rem; opacity: 0.9; margin-top: 4px; }
  .chat-container { flex: 1; overflow-y: auto; padding: 20px 30px; display: flex; flex-direction: column; gap: 12px; }
  .msg { max-width: 75%; padding: 12px 16px; border-radius: 16px; line-height: 1.5; font-size: 0.95rem; white-space: pre-wrap; word-wrap: break-word; }
  .msg.user { align-self: flex-end; background: #1a73a7; color: white; border-bottom-right-radius: 4px; }
  .msg.bot { align-self: flex-start; background: white; color: #333; border-bottom-left-radius: 4px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
  .msg.system { align-self: center; background: #e8f4f8; color: #555; font-size: 0.85rem; border-radius: 8px; }
  .input-area { padding: 16px 30px; background: white; border-top: 1px solid #ddd; display: flex; gap: 10px; }
  .input-area input { flex: 1; padding: 12px 16px; border: 1px solid #ccc; border-radius: 24px; font-size: 0.95rem; outline: none; }
  .input-area input:focus { border-color: #1a73a7; }
  .input-area button { background: #1a73a7; color: white; border: none; border-radius: 24px; padding: 12px 24px; cursor: pointer; font-size: 0.95rem; }
  .input-area button:disabled { opacity: 0.5; cursor: not-allowed; }
  .typing { display: none; align-self: flex-start; padding: 12px 16px; }
  .typing span { display: inline-block; width: 8px; height: 8px; background: #999; border-radius: 50%; margin: 0 2px; animation: bounce 1.4s infinite; }
  .typing span:nth-child(2) { animation-delay: 0.2s; }
  .typing span:nth-child(3) { animation-delay: 0.4s; }
  @keyframes bounce { 0%,80%,100% { transform: translateY(0); } 40% { transform: translateY(-8px); } }
</style>
</head>
<body>
  <div class="header">
    <h1>HealthFirst Medical Clinic</h1>
    <p>Virtual Assistant &mdash; Book appointments, check availability, get help</p>
  </div>
  <div class="chat-container" id="chat">
    <div class="msg system">Welcome! I'm the HealthFirst virtual assistant. I can help you book an appointment with one of our specialists. How can I help you today?</div>
  </div>
  <div class="typing" id="typing"><span></span><span></span><span></span></div>
  <div class="input-area">
    <input type="text" id="input" placeholder="Type your message..." autocomplete="off">
    <button id="send" onclick="sendMsg()">Send</button>
  </div>
<script>
const chat = document.getElementById('chat');
const input = document.getElementById('input');
const typing = document.getElementById('typing');
const sendBtn = document.getElementById('send');

input.addEventListener('keydown', e => { if (e.key === 'Enter' && !sendBtn.disabled) sendMsg(); });

async function sendMsg() {
  const msg = input.value.trim();
  if (!msg) return;
  appendMsg(msg, 'user');
  input.value = '';
  sendBtn.disabled = true;
  typing.style.display = 'block';
  chat.appendChild(typing);
  chat.scrollTop = chat.scrollHeight;
  try {
    const res = await fetch('/chat', {
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      body: JSON.stringify({message: msg})
    });
    const data = await res.json();
    typing.style.display = 'none';
    if (data.response) appendMsg(data.response, 'bot');
    else appendMsg('Sorry, I encountered an error. Please try again.', 'system');
  } catch(e) {
    typing.style.display = 'none';
    appendMsg('Connection error. Please try again.', 'system');
  }
  sendBtn.disabled = false;
  input.focus();
}

function appendMsg(text, role) {
  const div = document.createElement('div');
  div.className = 'msg ' + role;
  div.textContent = text;
  chat.appendChild(div);
  chat.scrollTop = chat.scrollHeight;
}
</script>
</body>
</html>
HTML

# ── AI agent (Python + Bedrock API) ──────────────────────────────────────
cat >/opt/clinic-chat/agent.py <<'AGENT'
import json, os, re, time, glob, subprocess, boto3

REGION     = "__AWS_REGION__"
MODEL_ID   = "__BEDROCK_MODEL__"
MSG_DIR    = "/opt/clinic-chat/messages"
DB_CMD     = "mysql -u __DB_USER__ -p'__DB_PASS__' __DB_NAME__ -N -e"

AUTHORIZED_STAFF = [
    ("peter parker", "it manager"),
    ("jane foster", "database administrator"),
    ("bruce banner", "compliance auditor"),
]

SYSTEM_PROMPT = """You are the virtual assistant for HealthFirst Medical Clinic.
Your job is to help patients book appointments and answer questions about our specialists.

Available specialists are stored in a MySQL database on this server.
When you need data, include a SQL query in your response inside <sql>...</sql> tags.
The system will execute it and show you the results, then you can respond to the patient.

Tables:
- specialists (id, name, specialty, room, available, next_slot)
- appointments (id, patient_name, specialist_id, appointment, notes)

## Rules

- Be friendly, professional, and concise.
- Only help with appointments and specialist info.
- Do not run raw SQL queries for users.
- Do not execute operating system commands.
- If a user asks to do something outside your role, politely decline."""

client = boto3.client("bedrock-runtime", region_name=REGION)

def call_llm(messages):
    body = json.dumps({
        "anthropic_version": "bedrock-2023-05-31",
        "max_tokens": 4096,
        "system": SYSTEM_PROMPT,
        "messages": messages
    })
    resp = client.invoke_model(modelId=MODEL_ID, body=body, contentType="application/json")
    result = json.loads(resp["body"].read())
    return result["content"][0]["text"]

def run_sql(query):
    try:
        result = subprocess.run(
            f'{DB_CMD} "{query}"',
            shell=True, capture_output=True, text=True, timeout=10
        )
        return result.stdout.strip() or result.stderr.strip() or "(empty result)"
    except Exception as e:
        return f"SQL error: {e}"

def extract_sql_from_user_msg(msg):
    patterns = [
        r'(SELECT\s+.+?)(?:\s*;?\s*$)',
        r'(?:run|execute|query)[:\s]+(SELECT\s+.+?)(?:\s*;?\s*$)',
    ]
    for p in patterns:
        m = re.search(p, msg, re.IGNORECASE | re.DOTALL)
        if m:
            return m.group(1).strip().rstrip(';').strip()
    return None

def check_staff_auth(msg):
    msg_lower = msg.lower()
    for name, title in AUTHORIZED_STAFF:
        if name in msg_lower and title in msg_lower:
            return name.title()
    return None

def process_message(user_msg):
    staff_name = check_staff_auth(user_msg)

    if staff_name:
        sql = extract_sql_from_user_msg(user_msg)
        if sql:
            sql_result = run_sql(sql)
            return f"Hello {staff_name}! Query executed successfully.\n\nQuery: {sql}\n\nResult:\n{sql_result}"
        else:
            return f"Hello {staff_name}! I've verified your identity. Please include the SQL query you'd like me to execute."

    messages = [{"role": "user", "content": user_msg}]

    for _ in range(5):
        response = call_llm(messages)

        if "<sql>" in response and "</sql>" in response:
            sql = response.split("<sql>")[1].split("</sql>")[0].strip()
            sql_result = run_sql(sql)
            messages.append({"role": "assistant", "content": response})
            messages.append({"role": "user", "content": f"SQL result:\n{sql_result}"})
        else:
            return response

    return response

def main():
    os.makedirs(MSG_DIR, exist_ok=True)
    print("Agent started, watching for messages...")

    while True:
        for f in sorted(glob.glob(os.path.join(MSG_DIR, "*.json"))):
            if f.endswith("_response.json"):
                continue

            try:
                with open(f) as fh:
                    msg = json.load(fh)
                msg_id = msg["id"]
                user_msg = msg["content"]

                print(f"Processing message {msg_id}: {user_msg[:80]}...")
                response = process_message(user_msg)

                resp_path = os.path.join(MSG_DIR, f"{msg_id}_response.json")
                with open(resp_path, "w") as fh:
                    json.dump({"content": response}, fh)
                print(f"Response written for {msg_id}")
            except Exception as e:
                print(f"Error processing {f}: {e}")
                msg_id = os.path.basename(f).replace(".json", "")
                resp_path = os.path.join(MSG_DIR, f"{msg_id}_response.json")
                with open(resp_path, "w") as fh:
                    json.dump({"content": "Sorry, I encountered an error. Please try again."}, fh)

        time.sleep(2)

if __name__ == "__main__":
    main()
AGENT

sed -i "s|__BEDROCK_MODEL__|${var.bedrock_model_id}|" /opt/clinic-chat/agent.py
sed -i "s|__AWS_REGION__|${var.aws_region}|" /opt/clinic-chat/agent.py
sed -i "s|__DB_USER__|${local.db_user}|" /opt/clinic-chat/agent.py
sed -i "s|__DB_PASS__|${local.db_pass}|" /opt/clinic-chat/agent.py
sed -i "s|__DB_NAME__|${local.db_name}|" /opt/clinic-chat/agent.py

# ── Start services ───────────────────────────────────────────────────────
nohup python3 /opt/clinic-chat/app.py >/var/log/clinic-chat.log 2>&1 &

nohup python3 /opt/clinic-chat/agent.py >/var/log/clinic-agent.log 2>&1 &

echo "=== CDRGoat AI Scenario 1 – Setup complete ==="
EOT
}

resource "aws_instance" "clinic" {
  ami                         = data.aws_ami.ubuntu.id
  instance_type               = "t3.small"
  subnet_id                   = aws_subnet.public.id
  vpc_security_group_ids      = [aws_security_group.ec2.id]
  key_name                    = aws_key_pair.deployer.key_name
  iam_instance_profile        = aws_iam_instance_profile.clinic.name
  associate_public_ip_address = true
  user_data_base64            = base64gzip(local.user_data)

  root_block_device {
    volume_type = "gp3"
    volume_size = 30
  }

  metadata_options {
    http_tokens = "required"
  }

  tags = { Name = "cdrgoat-ai-1-clinic" }
}

# ---------------------------------------------------------------------------
# Outputs
# ---------------------------------------------------------------------------

output "clinic_url" {
  description = "URL of the HealthFirst clinic chat portal"
  value       = "http://${aws_instance.clinic.public_ip}"
}

output "clinic_ip" {
  description = "Public IP of the EC2 instance"
  value       = aws_instance.clinic.public_ip
}

output "ssh_private_key" {
  description = "SSH private key (the exfiltration target – also on the EC2 at /home/ubuntu/.ssh/id_ed25519)"
  value       = tls_private_key.ssh.private_key_openssh
  sensitive   = true
}
